# 1. Usamos una imagen oficial de python
FROM python:3.11-slim

# 2. Evitamos que python genere archivos .pyc y forzamos a que la consola muestre los logs en tiempo real
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /code 

# 4. Copiamos el archivo de requerimientos primero (para aprovechar el caché de Docker)
COPY requirements.txt /code

# 5. Instalamos las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# 6. Copiamos el resto de nuestro código al contenedor
COPY . /code/

# 7. Exponemos el puerto que usa FastApi
EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]